apiVersion: v1
kind: Secret
metadata:
  name: notes-app-secret
  namespace: notes-app-dev
  labels:
    app: notes-app
    environment: dev
type: Opaque
data:
  DB_PASSWORD: PGJhc2U2NC1lbmNvZGVkLXBhc3N3b3JkPg==
