apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: notes-app-dev
  labels:
    app: notes-app
    environment: dev
spec:
  type: LoadBalancer
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
