name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  # ==========================================
  # REPLACE THESE 2 VALUES WITH YOUR ACTUAL NAMES
  # ==========================================
  ECS_CLUSTER: "notes-app-cluster"
  ECS_SERVICE: "notes-app-task-service-a6pen5fq"
  # ==========================================
  
  AWS_ROLE_ARN: "arn:aws:iam::270926559765:role/GitHubActionsECSRole"
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: "notes-app"
  ECS_TASK_DEFINITION: "./task-definition.json"
  CONTAINER_NAME: "notes-app-container"

permissions:
  id-token: write # Required for secure OIDC authentication
  contents: read  # Required to checkout the code

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Render new image into task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true